import LZString from "lz-string";
import {
  STORAGE_KEYS,
  CERTIFICATE_POPUP_DELAY_MS,
} from "./config";
import { getElement } from "./dom-utils";

declare global {
  interface Window {
    setBG: (type: string) => void;
    closeCert: () => void;
    skipFlash: () => void;
    downloadPage: () => void;
    shareLink: () => void;
    shareOnX: () => void;
  }
}

document.addEventListener("DOMContentLoaded", () => {
  // Priority: URL hash (shared link) > localStorage (just generated)
  const hashData = window.location.hash.slice(1);
  let transformed: string | null = null;
  let devName = "Developer";
  let isSharedView = false;

  if (hashData) {
    try {
      const decompressed = LZString.decompressFromEncodedURIComponent(hashData);
      if (decompressed) {
        transformed = decompressed;
        isSharedView = true;
        // Try to extract a name from the HTML for the certificate
        const nameMatch = decompressed.match(/WELCOME TO ([^'<!\n]+?)['s ]/i);
        if (nameMatch) devName = nameMatch[1].trim();
      }
    } catch {
      // Bad hash, fall through to localStorage
    }
  }

  if (!transformed) {
    transformed = localStorage.getItem(STORAGE_KEYS.transformed);
    devName = localStorage.getItem(STORAGE_KEYS.devName) ?? "Developer";
  }

  const threat = localStorage.getItem(STORAGE_KEYS.threat);
  const outputDiv = getElement<HTMLDivElement>("transformed-content");

  // Personalize certificate
  const certThreat = document.getElementById("cert-threat");
  const certDevName = document.getElementById("cert-dev-name");
  const certPath = document.getElementById("cert-path");
  const certName = document.getElementById("cert-name");
  const memoSubject = document.getElementById("memo-subject");
  const memoName = document.getElementById("memo-name");

  if (certThreat) certThreat.textContent = threat ?? "Classified";
  if (certDevName) certDevName.textContent = devName;
  if (certPath) certPath.textContent = devName.replace(/\s+/g, "").toLowerCase();
  if (certName) certName.textContent = `"${devName}'s Kool Homepage 1997!!!!"`;
  if (memoSubject) memoSubject.textContent = devName;
  if (memoName) memoName.textContent = devName;

  // Hit counter
  const count = localStorage.getItem(STORAGE_KEYS.visitorCount) ?? "000249";
  const counterDisplay = document.querySelector(".counter-digits");
  if (counterDisplay) {
    counterDisplay.textContent = String(count).padStart(6, "0");
  }

  if (transformed) {
    outputDiv.innerHTML = transformed;
    console.log("\u{1F989} O.W.L.S. - 1997 Content Restored.");
  } else {
    outputDiv.innerHTML =
      "<p>ERROR 418: Identity Reassignment failed. Agent Hoot has lost the dossier. Please return to HQ.</p>";
  }

  // === FEATURE 1: Download as standalone HTML ===
  window.downloadPage = () => {
    if (!transformed) return;
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${devName}'s Kool Homepage 1997!!!!</title>
<style>
body { font-family: "Comic Sans MS", "Comic Sans", cursive; background-color: #000; color: #fff; margin: 0; }
table { border-collapse: separate; }
marquee { display: block; }
a { color: #00FFFF; }
a:visited { color: #FF69B4; }
hr { border-color: #FF00FF; }
</style>
</head>
<body>
${transformed}
<hr>
<center>
<p><font size="2" color="#888888">Generated by <a href="https://devcities.lol">devCities.lol</a> — O.W.L.S. Witness Protection Program</font></p>
<p><font size="1" color="#666666">Agent Hoot approved this page. Badge #1997-🦉-001</font></p>
</center>
</body>
</html>`;
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${devName.replace(/\s+/g, "-").toLowerCase()}-1997.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // === FEATURE 2: Share via URL hash ===
  window.shareLink = () => {
    if (!transformed) return;
    const compressed = LZString.compressToEncodedURIComponent(transformed);
    const shareUrl = `${window.location.origin}${window.location.pathname}#${compressed}`;
    navigator.clipboard.writeText(shareUrl).then(() => {
      const btn = getElement("share-link-btn");
      btn.textContent = "\u2705 Link Copied!!!!";
      btn.classList.add("copied");
      setTimeout(() => {
        btn.textContent = "\u{1F517} Copy Link";
        btn.classList.remove("copied");
      }, 3000);
    });
  };

  // === Share on X ===
  window.shareOnX = () => {
    const text = `Agent Hoot just built me a 1997 dev portfolio.\nI am now in witness protection. 🦉\n\nhttps://devcities.lol`;
    const tweetUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`;
    window.open(tweetUrl, "_blank", "width=600,height=400");
  };

  // Global controls for inline onclick handlers
  window.setBG = (type: string) => {
    document.body.className = type;
  };
  window.closeCert = () => {
    getElement("certificate-popup").classList.add("hidden");
  };
  window.skipFlash = () => {
    getElement("flash-intro-box").classList.add("hidden");
  };

  // Auto-pop certificate (skip on shared views to not annoy visitors)
  if (!isSharedView) {
    setTimeout(() => {
      const cert = document.getElementById("certificate-popup");
      if (cert) cert.classList.remove("hidden");
    }, CERTIFICATE_POPUP_DELAY_MS);
  }
});
